services:
  - type: web
    name: lead-generation-automation
    env: node
    plan: free
    buildCommand: npm ci --only=production --no-audit --no-fund --prefer-offline
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: APIFY_API_TOKEN
        sync: false
      - key: OPENAI_API_KEY  
        sync: false
      - key: MAX_REQUESTS_PER_MINUTE
        value: 10
      - key: MAX_LEADS_PER_REQUEST
        value: 500
      # Microsoft Graph Integration Variables
      - key: AZURE_TENANT_ID
        sync: false
      - key: AZURE_CLIENT_ID
        sync: false  
      - key: AZURE_CLIENT_SECRET
        sync: false
      - key: RENDER_EXTERNAL_URL
        value: https://lead-generation-automation.onrender.com
    healthCheckPath: /
    # Optimize build settings
    buildPhase: 
      commands:
        - npm ci --only=production --no-audit --no-fund
    # Add disk space optimization
    disk: 512